FROM mariadb:10.11

LABEL org.opencontainers.image.source=https://github.com/u2waremanager/io.u2ware.examples.env
LABEL org.opencontainers.image.description="mariadb 10.11 with common environment settings for U2ware"
