FROM mcr.microsoft.com/mssql/server:2025-latest


LABEL org.opencontainers.image.source=https://github.com/u2waremanager/io.u2ware.examples.env
LABEL org.opencontainers.image.description="MSSQL Server2025-latest with common environment settings for U2ware"
